---
- name: find  contents of a directory
  hosts: all
  become: true
  vars_files:
      - vault.yml
  vars:
    target_dir: /var/
  tasks:
    - name: Find all files and directories under the target directory
      find:
        paths: "{{ target_dir }}"
        file_type: directory
        recurse: no
      register: found_items
    - name: Record output
      debug:
        var: found_items  
