---
- hosts: all
  become: true
  tasks:
    - name: check file existt
      ansible.builtin.stat:
        path: /etc/test1.html
      register: index_stat
    - name: Install httpd
      ansible.builtin.dnf:
        name: httpd
        state: present
    - name: Try to copy test.html if it exists
      ansible.builtin.copy:
        src: /etc/test.html
        dest: /var/www/html/test.html
        owner: root
        group: root
        mode: '0644'
      when: index_stat.stat.exists
