vars:
    config_lines:
      - "[client]"
      - " user=root"
      - "password=RootPass123!"
      - "host=127.0.0.1"
      - "socket=/var/lib/mysql/mysql.sock"
  tasks:
    - name: Ensure each config line is present
      ansible.builtin.lineinfile:
        path: /root/.my.cnf
        line: "{{ item }}"
        state: present
        create: yes
      loop: "{{ config_lines }}"
